### PR TITLE
docs(core): Added description of benchmark

### PR DESCRIPTION
**Pull request by EdamAme-x**
I forgot to sync, so I am reposting.
sorry.

### CODE REVIEW

**Comment by Boshen** [comment]
The tone of this PR is a bit too much, I'll have to refuse the addition here, sorry :-(.

**Comment by EdamAme-x** [comment]
ok...

**Comment by NozomuIkuta** [comment]
@EdamAme-x 

Thank you for submitting the PR.

By the way, just in case for your information, you don't have to close and create another PR if you want to just fix some parts of the original PR. 

It's a common practice to push commits to the original PR, and/or merge `main` branch resolve conflicts as needed.

**Comment by EdamAme-x** [comment]
sorry...
However, for some reason, I couldn't send the commit to this branch because of an error.

**Pull request closed without merging**
