### PR TITLE
feat: implement RSS & Atom feeds for the English-language blog

### LINKED ISSUE #104: RSS support for the blog
Please add RSS/Atom support so we can follow...

### PR DESCRIPTION
**Pull request by gBasil**
Fixes #104

### Notes

- Only implements RSS & Atom feeds for the English blog.
- It is only available via `<link>` tags in the header (RSS autodiscovery), and isn't linked to anywhere on the website.
- It will throw an error if it cannot find a date for a blog post, which is a breaking change from what previous date-handling code for this website does.
- I don't know what decisions you want to make (what title to use for the feeds, what path the feeds should be located at, etc.), so this PR is to get the ball rolling.
  - I'm likely not going to implement feeds for the other languages, as I'm not entirely sure how those should be handled.

### CODE REVIEW

**Comment by Boshen** [comment]
> I'm likely not going to implement feeds for the other languages

I'm undecided on supporting more languages either, it's currently half baked 😅 

> what title to use for the feeds, what path the feeds should be located at

I don't know the details about RSS feeds, so can I delegate this decision to you, and we'll just stick with it?

**Comment by gBasil** [comment]
> > what title to use for the feeds, what path the feeds should be located at
>
> I don't know the details about RSS feeds, so can I delegate this decision to you, and we'll just stick with it?

Alright :) The reason I brought that up was because I wasn't sure how you wanted to handle multiple languages (since I think you have some sort of subdirectory system going, which would mean changing the location of the feeds). RSS feeds can be at any path.

**Comment by Boshen** [comment]
I see, shall we go for something like `/en/feeds/blog.atom`?

**Comment by gBasil** [comment]
Up to you. I'd say keep it consistent with the localization. English seems to be at the root right now, so I'd think keeping the English feed at the root level unless you want to change that to be under `/en` (which might honestly look quite nice).

However, if you want to have it under `/en/feeds/blog.{atom,rss}` and maybe eventually migrate the English localization to `/en` sometime in the vague future, that would also work :)

**Comment by Boshen** [comment]
> Up to you. I'd say keep it consistent with the localization. English seems to be at the root right now, so I'd think keeping the English feed at the root level unless you want to change that to be under `/en` (which might honestly look quite nice).
> 
> However, if you want to have it under `/en/feeds/blog.{atom,rss}` and maybe eventually migrate the English localization to `/en` sometime in the vague future, that would also work :)

I see, let's stick with `/feeds/blog.atom`. Thank you for the explanation.

**Comment by gBasil** [comment]
I should also mention that it's good to have the feeds stay on one URL so folks don't have to update their feed readers to a new URL (or at least alert folks in some way of the new RSS URL). I think a redirect would also work, if that's a bridge that ever gets crossed.

Also, thanks for merging! :D Oxc is a super groovy project and I had been wanting to follow it via a feed for a while.

**Pull request merged**
